### ISSUE TITLE
Failed to load the java-importer package

### ISSUE THREAD

**Issue by mf275** [CodeMySky/java-importer#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 10 Pro
**Thrown From**: [java-importer](https://github.com/CodeMySky/java-importer) package, v1.4.0
### Stack Trace

Failed to load the java-importer package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\Morteza\AppData\Local\atom\app-1.0.11\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\Morteza\.atom\packages\CodeMySky-java-importer-1b09709\lib\java-importer-view.coffee:1:20)
    at Object.<anonymous> (C:\Users\Morteza\.atom\packages\CodeMySky-java-importer-1b09709\lib\java-importer-view.coffee:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Morteza\AppData\Local\atom\app-1.0.11\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atom-space-pen-views, v2.1.0

# Dev
No dev packages
```

**Comment by CodeMySky** [comment]
Hi,
   Sorry I don't have a Windows computer to reproduce the problem.
   I have updated my package to use exact version of atom-space-pen-views v2.1.0
   Please update and see if the issue is resolved.

Sean
