### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filePath' of null

### ISSUE THREAD

**Issue by drem-darios** [CodeMySky/java-importer#7]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.3
**Thrown From**: [java-importer](https://github.com/CodeMySky/java-importer) package, v1.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'filePath' of null

```
At /Users/bob/.atom/packages/java-importer/lib/java-importer-model.coffee:47

TypeError: Cannot read property 'filePath' of null
    at /Users/bob/.atom/packages/java-importer/lib/java-importer-model.coffee:47:24
    at didError (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:972:22)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:126:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:78:34)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -5:31.5.0 core:close (atom-pane.pane.active)
     -5:22.8.0 atom-beautify:beautify-editor (ul.list-inline.tab-bar.inset-panel)
     -5:11.8.0 core:undo (atom-text-editor.editor.is-focused)
     -5:09.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -5:07.7.0 core:copy (atom-text-editor.editor.is-focused)
     -2:55.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:54.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:50.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -2:50 core:move-left (atom-text-editor.editor.is-focused)
     -2:49.2.0 core:select-all (atom-text-editor.editor.is-focused)
     -2:48.5.0 core:copy (atom-text-editor.editor.is-focused)
     -2:48.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:09.8.0 core:paste (atom-text-editor.editor.is-focused)
  5x -1:09.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:08.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:07.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.14 (active)
auto-detect-indentation, v1.3.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-java, v1.2.5 (active)
highlight-selected, v0.11.2 (active)
java-importer, v1.4.1 (active)
linter, v1.11.18 (active)
linter-javac, v1.9.4 (active)
open-recent, v5.0.0 (active)
todo-show, v1.8.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (active)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by ToSeven** [comment]
I have the same issues with you ,but I do not konw how to solve it

**Comment by drem-darios** [comment]
I have a feeling this has to do with permissions. I was having issues with other plugins not being able to execute system commands because they required sudo.

**Comment by mlewando** [comment]
I have the same problem on windows system. Does anyone know the solution for this?

**Comment by pilattebe** [comment]
Same problem when typing 'Atom "path/to/project/folder"'

**Comment by hanbing5210** [comment]
this package likes for all files. even the file is not .java
